## Outras operações com Arrays

In [4]:
import numpy as np


dados = np.diag(np.arange(3))

dados

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [5]:
dados[1, 1]

1

In [8]:
b = np.arange(10)

b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b[2:9:3]

array([2, 5, 8])

In [11]:
b.max()

9

In [12]:
b.min()

0

In [13]:
a = np.array([1.2, 1.5, 11.6, 2.5, 3.5, 4.5])

a

array([ 1.2,  1.5, 11.6,  2.5,  3.5,  4.5])

In [14]:
np.around(a)

array([ 1.,  2., 12.,  2.,  4.,  4.])

In [16]:
c = a.flatten()

c

array([ 1.2,  1.5, 11.6,  2.5,  3.5,  4.5])

In [17]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.tile(b, 3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.repeat(b, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])