## Exercícios

### Crie um array NumPy com 1000000 e uma lista com 1000000. Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time). Qual objeto oferece melhor performance, array NumPy ou lista?

In [1]:
import numpy as np
import time 

array1 = np.arange(1, 1000000)
lista1 = list(range(1, 1000000))

#--- Multiplicando cada elemento por 2

#-- ARRAY

tempo_inicial_array = time.time()

array2 = array1 * 2

print("O tempo do array foi de: ", time.time() - tempo_inicial_array)

O tempo do array foi de:  0.004000186920166016


In [2]:
#-- LISTA

tempo_inicial_lista = time.time()

lista2 = list(map(lambda x: x * 2, lista1))

print("O tempo da lista array foi de: ", time.time() - tempo_inicial_lista)

O tempo da lista array foi de:  0.21222925186157227


### Crie um array de 10 elementos. Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [3]:
array3 = np.arange(1, 11)

array3[4:8] = 0

array3

array([ 1,  2,  3,  4,  0,  0,  0,  0,  9, 10])

### Crie um array de 3 dimensões e imprima a dimensão 1

In [4]:
array4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

array4[0, ]

array([1, 2, 3, 4])

### Crie um array de duas dimensões (matriz). Imprima os elementos da terceira linha da matriz. Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [5]:
array5 = np.array([[1, 2, 3], [4, 5, 6], [9, 10, 11]])

array5[2, ]
array5[0:, 1:]

array([[ 2,  3],
       [ 5,  6],
       [10, 11]])

### Calcule a transposta da matriz abaixo

arr = np.arange(15).reshape((3, 5))

arr

In [6]:
arr = np.arange(15).reshape((3, 5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Considere os 3 arrays abaixo. Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [8]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

for i, j, k in zip(xarr, yarr, cond):
    print(i, j, k)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


### Crie um array A com 10 elementos e salve o array em disco com a extensão npy. Depois carregue o array do disco no array B

In [9]:
array_a = np.arange(0, 10, 1)

np.save('array_a.npy', array_a)

np.load('array_a.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### # Considerando a série abaixo, imprima os valores únicos na série

import pandas as pd

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [10]:
import pandas as pd

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

obj.unique

<bound method Series.unique of 0     c
1     a
2     d
3     a
4     a
5     b
6     b
7     c
8     c
9     a
10    b
dtype: object>