# Carregando as bibliotecas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configurações adicionais

In [2]:
plt.style.use("seaborn-muted")
%matplotlib inline
pd.set_option('display.max_columns', None)

# Carregando o banco de dados

In [3]:
banco = pd.read_excel("dataset.xlsx")

In [4]:
banco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570 entries, 0 to 569
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   ID             570 non-null    int64  
 1   Place          570 non-null    object 
 2   Cod_cycle      570 non-null    int64  
 3   Zone           570 non-null    int64  
 4   cota           570 non-null    float64
 5   prof_local(m)  570 non-null    float64
 6   Mes            570 non-null    int64  
 7   Year           570 non-null    int64  
 8   Temp           564 non-null    float64
 9   TotalP         570 non-null    float64
 10  Chl            570 non-null    float64
 11  Secchi         570 non-null    float64
 12  Turbidity      570 non-null    float64
 13  STS            570 non-null    float64
 14  DO             570 non-null    float64
 15  OrthoP (mg/L)  550 non-null    float64
 16  Ammonium       570 non-null    float64
dtypes: float64(11), int64(5), object(1)
memory usage: 75.8

In [5]:
banco["Zone"].value_counts()

0    202
1    195
2    173
Name: Zone, dtype: int64

## Valores nulos

In [6]:
banco.isnull().sum()

ID                0
Place             0
Cod_cycle         0
Zone              0
cota              0
prof_local(m)     0
Mes               0
Year              0
Temp              6
TotalP            0
Chl               0
Secchi            0
Turbidity         0
STS               0
DO                0
OrthoP (mg/L)    20
Ammonium          0
dtype: int64

In [7]:
banco = banco.dropna()

## OneHotEncoding para a variável Place

In [8]:
banco = pd.get_dummies(data = banco, columns = ["Place", "Cod_cycle", "Mes", "Year"])

## Selecionando variáveis

In [9]:
# var = ["Zone", "prof_local(m)", "Temp", "TotalP", "Chl", "Secchi ", "Turbidity", "STS", "DO", "OrthoP (mg/L)", "Ammonium"]

# banco[var]


banco = banco.drop("ID", axis = 1)

In [10]:
x = banco.drop("Zone", axis = 1)
y = banco["Zone"]

banco.head()

Zone   cota  prof_local(m)  Temp  TotalP   Chl  Secchi   Turbidity  STS  \
0     0  73.86          30.00  30.4   15.34  4.76      3.0       2.18  1.0   
1     0  73.86          30.00  30.2   18.91  4.05      2.1       2.96  0.6   
2     0  73.69          30.00  29.5   20.70  5.95      2.5       2.90  2.8   
3     0  73.67          30.40  31.6   19.94  5.95      1.2      10.10  0.6   
4     0  62.58          19.17  29.8    5.79  3.45      2.6       1.52  2.0   

     DO  OrthoP (mg/L)  Ammonium  Place_C1  Place_C2  Place_M1  Place_M3  \
0  7.30          16.18     35.39         1         0         0         0   
1  5.86          15.81     23.50         1         0         0         0   
2  6.56           5.44     75.84         1         0         0         0   
3  7.82           9.51     23.50         1         0         0         0   
4  6.05           0.24     12.91         1         0         0         0   

   Place_M5  Place_MB  Place_MBB  Place_MI  Place_MJV  Place_ML  Place_MP  \
0         0         0          0         0          0         0         0   
1         0         0          0         0          0         0         0   
2         0         0          0         0          0         0         0   
3         0         0          0         0          0         0         0   
4         0         0          0         0          0         0         0   

   Place_MR  Cod_cycle_0  Cod_cycle_1  Cod_cycle_2  Cod_cycle_3  Mes_1  Mes_2  \
0         0            0            0            1            0      0      0   
1         0            0            0            1            0      0      0   
2         0            0            0            1            0      0      0   
3         0            0            0            1            0      0      0   
4         0            0            1            0            0      0      0   

   Mes_3  Mes_4  Mes_5  Mes_6  Mes_7  Mes_8  Mes_9  Mes_10  Mes_11  Mes_12  \
0      0      1      0      0      0      0      0       0       0       0   
1      0      1      0      0      0      0      0       0       0       0   
2      0      1      0      0      0      0      0       0       0       0   
3      0      1      0      0      0      0      0       0       0       0   
4      0      0      0      0      0      0      0       0       0       1   

   Year_2006  Year_2007  Year_2008  Year_2009  Year_2010  Year_2011  \
0          0          0          0          0          0          0   
1          0          0          0          0          0          0   
2          0          0          0          0          0          0   
3          0          0          0          0          0          0   
4          1          0          0          0          0          0   

   Year_2012  Year_2013  Year_2014  Year_2015  Year_2016  
0          1          0          0          0          0  
1          0          1          0          0          0  
2          0          0          1          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

var = ["cota", "prof_local(m)", "Temp", "TotalP", "Chl", "Secchi ", "Turbidity", "STS", "DO", "OrthoP (mg/L)", "Ammonium"]

features = banco[var]

ct = ColumnTransformer([
        ('somename', StandardScaler(), var)
    ], remainder='passthrough')

banco[var] = ct.fit_transform(features)

banco = pd.concat([banco[var], banco["Zone"]], axis = 1)

banco.head()

cota  prof_local(m)      Temp    TotalP       Chl   Secchi   Turbidity  \
0  1.078716       0.069954  0.373204 -0.492684 -0.384398  0.775737  -0.466711   
1  1.078716       0.069954  0.152748 -0.292759 -0.536950 -0.088201  -0.412085   
2  1.046469       0.069954 -0.618850 -0.192517 -0.128713  0.295771  -0.416287   
3  1.042675       0.093635  1.695943 -0.235078 -0.128713 -0.952140   0.087954   
4 -1.060975      -0.571218 -0.288165 -1.027497 -0.665867  0.391764  -0.512933   

        STS        DO  OrthoP (mg/L)  Ammonium  Zone  
0 -0.478449  1.407356       0.865784 -0.113064     0  
1 -0.535160 -0.292216       0.819618 -0.369460     0  
2 -0.223246  0.533964      -0.474265  0.759199     0  
3 -0.535160  2.021090       0.033556 -0.369460     0  
4 -0.336670 -0.067967      -1.123078 -0.597823     0

## Separando em treino e teste

In [12]:
from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, train_size = 0.7, random_state = 1234)

In [13]:
x_treino.shape, y_treino.shape, x_teste.shape, y_teste.shape

((382, 50), (382,), (165, 50), (165,))

## Modelos

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier


#--- Random Forest

# rfc = RandomForestClassifier(n_estimators = 100, 
#                              random_state = 1234, 
#                              n_jobs = -1)

# 'test_accuracy': array([1.        , 1.        , 1.        , 0.94117647, 1.        ,
#         1.        , 0.9375    , 1.        , 1.        , 0.9375    ])}


#--- Regressão logística 

# rfc = LogisticRegression(random_state = 1234, n_jobs = -1)

# 'test_accuracy': array([0.88235294, 0.94117647, 0.82352941, 0.88235294, 0.94117647,
#         0.8125    , 0.8125    , 0.8125    , 0.8125    , 0.8125    ])}


#--- SVC


# rfc = SVC()

# 'test_accuracy': array([0.64705882, 0.52941176, 0.64705882, 0.58823529, 0.58823529,
#         0.3125    , 0.5625    , 0.5625    , 0.375     , 0.5625    ])}


#--- KNN

rfc = KNeighborsClassifier(n_neighbors = 3)

# 'test_accuracy': array([0.42857143, 0.64285714, 0.5       , 0.42857143, 0.2962963 ,
#         0.40740741, 0.66666667, 0.37037037, 0.55555556, 0.51851852])}

# Gaussian Naive Bayes

# rfc = GaussianNB()

# 'test_accuracy': array([0.71428571, 0.64285714, 0.75      , 0.64285714, 0.66666667,
#         0.48148148, 0.7037037 , 0.81481481, 0.7037037 , 0.7037037 ])}


# Perceptron

# rfc = Perceptron()

# 'test_accuracy': array([0.46428571, 0.32142857, 0.32142857, 0.32142857, 0.33333333,
#         0.2962963 , 0.33333333, 0.2962963 , 0.37037037, 0.2962963 ])}


# Linear SVC

# rfc = LinearSVC(max_iter = 500)

# test_accuracy': array([0.42857143, 0.57142857, 0.5       , 0.42857143, 0.51851852,
#         0.37037037, 0.44444444, 0.59259259, 0.48148148, 0.48148148])}


# Stochastic Gradient Descent

# rfc = SGDClassifier()

# 'test_accuracy': array([0.39285714, 0.39285714, 0.39285714, 0.35714286, 0.33333333,
#         0.40740741, 0.33333333, 0.59259259, 0.44444444, 0.37037037])}


# Decision Tree

# rfc = DecisionTreeClassifier(random_state = 1234)

# 'test_accuracy': array([0.75      , 0.64285714, 0.53571429, 0.64285714, 0.59259259,
#         0.40740741, 0.59259259, 0.66666667, 0.55555556, 0.74074074])}




## Cross Validation


In [30]:
%%time

from sklearn.model_selection import cross_validate 

scoring1 = [
     "accuracy"]

scores = cross_validate(rfc, x_teste, y_teste, cv = 10, scoring = scoring1, n_jobs = -1)

# print("Os scores são:", scores)

# print("Média dos scores:", scores.mean())

Wall time: 125 ms


In [31]:
scores

{'fit_time': array([0.00499892, 0.00499845, 0.00699568, 0.00499821, 0.00499749,
        0.00500083, 0.00499797, 0.00500131, 0.00500011, 0.00599957]),
 'score_time': array([0.00399899, 0.00500154, 0.00500011, 0.00599718, 0.00500178,
        0.00499606, 0.00500131, 0.00499678, 0.00499868, 0.00499821]),
 'test_accuracy': array([0.58823529, 0.64705882, 0.52941176, 0.52941176, 0.47058824,
        0.375     , 0.3125    , 0.4375    , 0.4375    , 0.4375    ])}

## Random Forest aplicado aos dados de teste

In [32]:
rfc.fit(x_treino, y_treino)

y_pred = rfc.predict(x_teste)

# Métricas a serem avaliadas


In [33]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_teste, y_pred)

print("Accuracy:", acc)

Accuracy: 0.47878787878787876


In [28]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_teste, y_pred))

[[42 15  2]
 [30 18  4]
 [20 18 16]]


In [20]:
pd.crosstab(y_teste, y_pred, rownames = ["True"], colnames = ["Predicted"], margins = True)

Predicted   0   1   2  All
True                      
0          36  15   8   59
1          16  20  16   52
2          11  13  30   54
All        63  48  54  165

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_teste, y_pred))

              precision    recall  f1-score   support

           0       0.57      0.61      0.59        59
           1       0.42      0.38      0.40        52
           2       0.56      0.56      0.56        54

    accuracy                           0.52       165
   macro avg       0.51      0.52      0.52       165
weighted avg       0.52      0.52      0.52       165



In [22]:
pd.DataFrame(rfc.feature_importances_, x_teste.columns).reset_index().rename(columns = {0: "Valor", "index": "Variável"}).sort_values("Valor", ascending = False).round(5)

AttributeError: 'KNeighborsClassifier' object has no attribute 'feature_importances_'